### ISSUE TITLE
PDF Publishing - S1000D-XSL-Stylesheets

### ISSUE THREAD

**Issue by Demostenus** [kibook/S1000D-XSL-Stylesheets#1]
Hi, sorry to make an issue on this repo.
I just have some questions about the S1000D-XSL-Stylesheets and how you used them to create the PDF.

I tried to use your instructions from S1000DXSL-README.pdf but I cannot get it to work.
Do you have maybe an updated version with newer instructions?

For now I get stuck with this message: 
`/usr/local/bin/s1kd2pdf: 115: fop: Permission denied`
I tried running the s1kd2pdf command with sudo, and also gave permissions to the folder to my current user, but nothing works.

If you have time, can you please make some new instructions on how to publish the publication to PDF ? 🙏

**Comment by Demostenus** [comment]
😭 
I had downloaded the binary from https://xmlgraphics.apache.org/fop/download.html
The installation instructions are confusing... 

`Instructions¶
Basic FOP installation consists of first unzipping the .gz file that is the distribution medium, then unarchiving the resulting .tar file in a directory/folder that is convenient on your system.`

That wasn't working so I just installed fop like this:
`sudo apt-get install -y fop`

Not fop -version says. "FOP Version 2.4"
Is this good enough ?

I tried again to publish a publication and now I get some other errors. 
I will check them and come back if I need some more help 😞

**Comment by kibook** [comment]
> That wasn't working so I just installed fop like this:

That's fine, it shouldn't matter where you get FOP from.

> Is this good enough ?

If `fop -version` outputs `FOP Version <version>` and not something like `fop: command not found`, then you should be good to go.

> I tried again to publish a publication and now I get some other errors.

If you have trouble, just post the errors here and I'll try to help!

**Comment by Demostenus** [comment]
No matter which publication I try to publish I get the same errors.
1. Some warnings about fop
2. PM references unknown


```
"[warning] /usr/bin/fop: JVM flavor 'sun' not understood
[warning] /usr/bin/fop: Unable to locate avalon-framework in /usr/share/java
PM references unknown DM: S1KDTOOLS-A-00-00-00-00A-001A-D
PM references unknown DM: S1KDTOOLS-A-00-00-00-00A-00SA-D
PM references unknown DM: S1KDTOOLS-A-00-00-00-00A-00UA-D
PM references unknown DM: S1KDTOOLS-A-00-00-00-00A-009A-D
PM references unknown DM: S1KDTOOLS-A-00-00-00-00A-005A-D
PM references unknown DM: S1KDTOOLS-A-00-00-00-00A-040B-D
PM references unknown DM: S1KDTOOLS-A-00-00-00-00A-018A-D
................"
```

**Comment by kibook** [comment]
The first two messages sound like a problem with the FOP installation, not directly related to these stylesheets.

Try this minimal XSL-FO example:
```xml
<?xml version="1.0"?>
<fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">
  <fo:layout-master-set>
    <fo:simple-page-master master-name="page">
      <fo:region-body/>
    </fo:simple-page-master>
  </fo:layout-master-set>
  <fo:page-sequence master-reference="page">
    <fo:flow flow-name="xsl-region-body">
      <fo:block>Hello, world!</fo:block>
    </fo:flow>
  </fo:page-sequence>
</fo:root>
```

Save it as "test.fo" and then run this command:
```
$ fop test.fo test.pdf
```

This should produce a minimal PDF with the text "Hello, world!" on it. If you still get those first two error messages, then it's not related to these stylesheets.

The remaining errors are what happens if the stylesheet can't find a referenced data module in the input. Are you running it directly on the publication module, like this?

```
$ s1kd2pdf PMC-S1KDTOOLS-KHZAE-00000-00_EN-CA.XML
```

The stylesheets don't try to search the filesystem for a data module, so you have to combine the PM and DMs into one input. The stylesheets support two methods:

- create an XML file with root element `<publication>`, containing XInclude references to the PM and all DMs
    ```xml
    <publication xmlns:xi="http://www.w3.org/2001/XInclude">
    <xi:include href="PMC-S1KDTOOLS-KHZAE-00000-00_EN-CA.XML"/>
    <xi:include href="DMC-S1KDTOOLS-A-00-00-00-00A-001A-D_EN-CA.XML"/>
    ...
    </publication>
    ```
- replace the `<dmRef>`s in the PM with XInclude refs to the DMS, or the actual contents of the DMs (element `<dmodule>`)
    ```xml
    <pm xmlns:xi="http://www.w3.org/2001/XInclude">
    ...
    <content>
    <pmEntry>
    <pmEntryTitle>Front matter</pmEntryTitle>
    <xi:include href="DMC-S1KDTOOLS-A-00-00-00-00A-001A-D_EN-CA.XML"/>
    ...
    </pmEntry>
    ...
    </content>
    </pm>
    ```

Both can be done automatically via the [s1kd-flatten](https://github.com/kibook/s1kd-tools/tree/master/tools/s1kd-flatten) tool.

You could try building the PDF using the [Makefile](https://github.com/kibook/s1kd-tools-doc/blob/master/Makefile) instead of directly using s1kd2pdf. In the checked out repo directory, run:

```
$ make
```

That's precisely what I do to build the documentation prior to each release.

**Comment by Demostenus** [comment]
I used the s1kd-flatten and then the s1kd2pdf and it published the PDF.
I tried it on your publication for the s1kd-tools pdf and there some issues:

1. The autogenerated pages are empty: Title page, List of effective pages, highlights, TOC. How are these created?
2. Also, the pdf bookmarks are not the same as your pdf. The first level bookmarks are missing. Front Matter, Introduction, Tools for generating data, etc... Are these edited manually?

**Comment by kibook** [comment]
> 1. The autogenerated pages are empty: Title page, List of effective pages, highlights, TOC. How are these created?

The stylesheet has options to generate the content of front matter DMs. To enable this, add these arguments to the **end** of the s1kd2pdf command:

```
-param generate.title.page 1
-param generate.highlights 1
-param generate.list.of.datamodules 1
-param generate.table.of.contents 1
```

You can see all the extra parameters I pass to the stylesheets at the top of the Makefile.

You can also use the s1kd-fmgen tool to generate the content of front matter DMs ahead of time. In that case you wouldn't enable those options, otherwise the stylesheet will just generate the contents a second time and overwrite what s1kd-fmgen did (though, only if you're using a descript schema DM instead of a frontmatter schema DM).

> 2. Also, the pdf bookmarks are not the same as your pdf. The first level bookmarks are missing. Front Matter, Introduction, Tools for generating data, etc... Are these edited manually?

This is controlled by the parameter `include.pmentry.bookmarks`. The default behaviour is to only create bookmarks for the DMs. To also get bookmarks based on the PM structure, use this:

```
-param include.pmentry.bookmarks 1
```

There's a brief description of each parameter in the manpage for s1kd2pdf, which if you installed it can be read with:

```
$ man s1kd2pdf
```

Or, you can check the README on the repo: [s1kd2pdf.README.md](https://github.com/kibook/S1000D-XSL-Stylesheets/blob/master/s1kd2pdf.README.md)

If you have any questions on what any of them do, though, feel free to create an issue or send me an email!

**Comment by Demostenus** [comment]
I did this on your publication and it worked.

I did it on mine publication and it also worked. There are some small issues though. 
But at least now I have some output, I have a good basis to work on. 
Thank you so much for your advises 🍻
